### ISSUE TITLE
The BASE_URL and and POST_URL has no description on what to put

### ISSUE THREAD

**Issue by renzified** [Farhandroid/AndroidCleanArchitecture#13]
I want to run the project but the I dont know what api version should i put on the BASE_URL and POST_URL please provide a better description thank you

**Comment by chukimmuoi** [comment]
This is probably what you need:
API_KEY="etc..."
BASE_URL="https://api.themoviedb.org/3/"
POSTER_URL = "https://image.tmdb.org/t/p/original/"
